### ISSUE TITLE
Some expressions in nogo.md need further clarification

### ISSUE THREAD

**Issue by andylizf** [panjd123/TurlingNoGo#21]
In the explanation of the rule,
> 如果一方落子后吃掉了对方的棋子，则落子一方判负（顾名不围棋）
> 对弈禁止自杀，落子自杀一方判负
> 注意：不可能平手，无处落子时只能认输或者自杀

There is an ambiguity on suiciding. According to the second sentence, it means to put a stone to be captured, then the last sentence should be modified to "无处落子时只能认输、自杀或吃掉对方的棋子".

**Comment by panjd123** [comment]
有道理

**Comment by panjd123** [comment]
我改成“有可能出现不得不输的局面，此时落子然后被判负或直接认输都可”
