### ISSUE TITLE
Clarify `Role` Field in Repeated `READY_OP` for Confirmation

### ISSUE THREAD

**Issue by andylizf** [panjd123/TurlingNoGo#45]
In the current protocol used by TuringNoGo, the repeated `READY_OP` operation is used for confirmation. However, the `Role` field for the repeated `READY_OP` is currently marked as optional in the protocol specification. This optional designation may cause confusion for the client, as it may interpret the repeated `READY_OP` as an application rather than a confirmation.

To improve clarity and prevent misinterpretation, it is recommended to update the protocol specification to clearly indicate that the `Role` field should be left empty when sending a repeated `READY_OP` for confirmation.

This clarification will prevent confusion on the client's side and ensure that the repeated `READY_OP` is correctly understood as a confirmation, even in cases where the initial `READY_OP` was lost or ignored.

This protocol change is expected to have minimal impact and should not cause significant changes or difficulties for most clients. Many existing clients already follow the practice of leaving the Role field empty when repeating `READY_OP` for confirmation purposes, even though it is not explicitly specified in the current protocol. By formally incorporating this behavior into the protocol specification, we aim to enhance the robustness and reliability of TuringNoGo and standardize the practice across all clients and provide clear guidance for future implementations.

**Comment by panjd123** [comment]
简单说，你的建议是希望修改协议中 `READY_OP` 的部分为：请求时数据段标记为颜色，确认时数据段留空，以区别
“A用户: 请求    B用户: 确认” 和 “A用户: 请求    B用户: 请求” 。

原则上来说，不改也可以，一方面，网络功能的最低要求中只需要客户端给服务端发请求；另一方面，如果不考虑时延，要求中指出了当收到对方的 `READY_OP` 时要禁发请求，而先让用户处理是否确认，而我们的通信协议都是基于不考虑时延的，也声明了这点假设。

如果考虑到时延，这确实是个问题，按照第二阶段的以下声明：

> 如果你的实现在协议中没有被定义，那你可以自己按照正常逻辑决定，但你需要保证其表现兼容现有的协议。

你只要保证自己的兼容自己的就可以。

因为你没有提出出现这种情况怎么解决，我就先按照我的想法写了一个处理方法到协议里了，但同样的，我们的要求仍然是你只要保证自己的兼容自己的就可以，如果你在其他组在测试时发现这个问题，大概率是一方没有按照要求中的 “当收到对方的 `READY_OP` 时要禁发请求，而先让用户处理是否确认” 来实现，数据包还在空中传的时候，双发互发是极小概率情况。

**Comment by MegaOwIer** [comment]
@panjd123 u1s1，你完全可以自己写一个根据某种规则胡乱发包的脚本来检测他们client的鲁棒性。我去年本来是想搞来着，后来事情有点多鸽了（
